print('Suma', 1 + 2)
print('Resta', 2 - 1)
print('Multiplicacion', 2 * 3)
print('Division', 4 / 2)
print('Division', 6 / 2)
print('Division', 7 / 2)
print('Division entera', 7 // 2)
print('Division entera', 7 // 3)
print('Modulo', 3 % 2)
print('Potencias', 2 ** 3)